site_name: PnP Modern Search (v4)
site_url: 'http://127.0.0.1:8000/'
use_directory_urls: true
nav:
  - Getting Started:
    - Introduction: index.md
    - Installation: installation.md
  
theme:
  name: 'material'
  features:
    - navigation.tabs
    - instant
  font:
    code: 'Ubuntu Mono'
  logo: 'assets/pnp_logo.png'
  icon:
    logo: material/cloud
extra_css:
  - 'assets/extra.css'
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_include.include:
          base_path: docs
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/m365pnp'
    - icon: fontawesome/brands/twitter
      link: 'https://github.com/gedeontofidji/Documentationbis/'
repo_url: https://github.com/gedeontofidji/Documentationbis
edit_uri: blob/develop/docs
